## 一、opencv-python读取、展示和存储图像

### 1、imread函数
读取数字图像  

`cv2.imread(path_of_image, intflag)`  
参数一： 需要读入图像的完整的路径  
参数二： 标志以什么形式读入图像，可以选择一下方式：

* cv2.IMREAD_COLOR： 加载彩色图像。任何图像的透明度都将被忽略。它是默认标志
* cv2.IMREAD_GRAYSCALE：以灰度模式加载图像
* cv2.IMREAD_UNCHANGED：保留读取图片原有的颜色通道


* 1 ：等同于cv2.IMREAD_COLOR
* 0 ：等同于cv2.IMREAD_GRAYSCALE
* -1 ：等同于cv2.IMREAD_UNCHANGED

In [1]:
import cv2
import imutils
import numpy as np

gray_img = cv2.imread('test.jpeg',0) # 加载灰度图像
rgb_img = cv2.imread('test.jpeg') # 加载RGB彩色图像
print("dd")

dd


### 2、imshow函数
在窗口显示图像，窗口自适应于图像大小，也可以通过imutils模块调整显示图像的窗口大小  

`cv2.imshow(window_name,image)`  
参数一：窗口名称 str  
参数二：图像对象 ndarray

In [2]:
cv2.imshow('origin image',rgb_img) # 显示原图
cv2.imshow('origin image size',imutils.resize(rgb_img,800)) # 利用imutils模块调整显示图像大小

### 3、imwrite函数
将图像保存到本地

`cv2.imwrite(image_filename,image)`  
参数一：保存的图像名称 str
参数二：图像对象 ndarray

In [ ]:
cv2.imwrite('rgb_img.jpg',rgb_img) # 将图像保存为jpg文件
cv2.imwrite('gray_img.png',gray_img) # 将图像保存为png文件 

### 4、窗口销毁函数
`cv2.destroyWindow(windows_name) # 销毁单个特定窗口`  
`cv2.destroyAllWindows() # 销毁全部窗口`

`cv2.waitKey(time_of_milliseconds)`  
参数大于0，等待的毫秒数；参数小于等于0，等待键盘敲击
```python
if cv2.waitKey(0) == 27: # ESC键
    cv2.destroyAllWindows()
if cv2.waitKey(-1) == ord('A'): # 键A
    cv2.destroyWindow('origin image')
```



In [2]:
import cv2
import imutils
import numpy as np

rgb_img = cv2.imread('test.jpeg')
gray_img = cv2.cvtColor(rgb_img, cv2.COLOR_BGR2GRAY)
cv2.imshow('origin image', imutils.resize(rgb_img, 800))
cv2.imshow('gray image', imutils.resize(gray_img, 800))
cv2.imwrite('rgb_img.jpg', rgb_img)
cv2.imwrite('gray_img.png', gray_img)

#等待一定时间自动销毁图像窗口
#if cv2.waitKey(10000):
#    cv2.destroyAllWindows()
#if cv2.waitKey(10000):
#    cv2.destroyWindow('origin image')

#接收特定键盘销毁图像窗口
if cv2.waitKey(-1) == ord('a'):
   cv2.destroyWindow('origin image')
if cv2.waitKey(0) == 27:
    cv2.destroyAllWindows()

## 二、色彩空间变换函数 cv2.cvtColor
`cv2.cvtColor(input_image,flag)`  
参数一：图像对象 ndarray  
参数二：图像色彩空间变换的类型
* cv2.COLOR_BGR2GRAY： 表示将图像从BGR空间转化成灰度图，最常用
* cv2.COLOR_BGR2HSV： 表示将图像从BGR空间转换到HSV空间


使用灰度图像的原因：  
图像的颜色主要是由于受到外界光照影响，我们做图像特征提取和识别过程时，我们要的是图像的梯度信息，也就是图像的本质内容，而颜色信息会对我们对梯度信息提取造成一定的干扰，因此我们会在做图像特征提取和识别前将图像转化为灰度图，这样同时也降低了处理的数据量并且增强了处理效果。

## 三、绘制自定义图像

### 1、绘制简单图像
对于一个BGR彩色图像，每个像素为(BGR)的一个元组，对于灰度图像，每个像素对应一个整数

In [5]:
import cv2
rgb_image = cv2.imread("test.jpeg")
# print(rbg_image)
print(rgb_image.shape) # (587, 900, 3) 高度587 宽度900
# rbg_image[0]中有900个[B G R]，有587个类同rbg_image[0]
print(rgb_image[0,0]) # [160 185 105]这是[0]的第一个[B G R]
print(rgb_image[0,899]) # [224 233 183]这是[0]的最后一个[B G R]
print(rgb_image[586,899]) # [114 117  61]这是[586]的最后一个[B G R]
print(rgb_image[0,0,1]) # 185 这是[0]的第一个B

gray_img=cv2.cvtColor(rgb_image,cv2.COLOR_BGR2GRAY)
# print(gray_img[0])
print(gray_img.shape) # (587, 900)
print(gray_img[0,0]) # 158


(587, 900, 3)
[160 185 105]
[224 233 183]
[114 117  61]
185
[158 160 163 164 165 168 172 175 172 176 180 182 183 185 187 190 195 196
 197 199 202 204 206 207 208 209 210 212 214 216 218 218 217 218 220 222
 224 225 225 225 232 231 229 227 225 225 225 225 229 226 223 223 226 233
 241 246 250 251 252 254 254 254 254 254 254 254 253 253 252 252 251 251
 250 249 249 247 246 246 246 246 247 245 246 245 243 242 241 240 241 239
 239 239 238 238 238 238 237 236 235 235 235 234 231 228 229 229 228 227
 226 225 225 224 225 225 224 222 221 220 219 218 217 215 212 210 210 209
 206 203 202 202 202 206 210 212 211 210 212 212 212 212 211 211 211 211
 203 204 206 207 206 205 203 201 197 195 191 186 181 177 173 171 163 156
 148 145 144 140 132 126 131 129 128 128 131 132 131 130 130 130 131 133
 136 137 134 131 139 139 138 137 136 135 135 134 138 137 137 137 139 142
 146 147 145 146 147 148 150 151 153 153 151 152 153 154 156 157 158 159
 159 160 161 162 163 165 166 166 166 168 170 171 170 170 172 174

In [1]:
### 2、对图像的简单像素操作

In [2]:
import cv2
import imutils
import numpy as np

rgb_img = cv2.imread('test.jpeg')
gray_img = cv2.cvtColor(rgb_img, cv2.COLOR_BGR2GRAY)

# 对图像取反
reverse_img = 255 - gray_img 

# 对图像像素线性变换
random_img = np.zeros((gray_img.shape[0], gray_img.shape[1]), dtype=np.uint8)
for i in range(gray_img.shape[0]):
    for j in range(gray_img.shape[1]):
        random_img[i, j] = gray_img[i, j]*1.2
        
cv2.imshow('reverse_img', imutils.resize(reverse_img, 800))
cv2.imshow('random_img', imutils.resize(random_img, 800))
if cv2.waitKey(0) == 27:
    cv2.destroyAllWindows()